name: Record temp/humidity
on:
  schedule:
    - cron: '*/30 * * * *' # every 30 minutes
  workflow_dispatch:

jobs:
  record:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5

      - run: |
          rustup override set stable
          rustup update stable

      - uses: Swatinem/rust-cache@v2

      - run: cargo run -p sebastian
        env:
          API_KEY: ${{ secrets.API_KEY }}
          DEVICE_ID: ${{ secrets.DEVICE_ID }}

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Record temp/humidity"
          git push
